### ISSUE TITLE
actual Video Frame Rate (FPS) is very different from what the settings says

### ISSUE THREAD

**Issue by zoff99** [uTox/uTox#1177]
### Overview

1. uTox version: latest
2. Operating system: Windows

the problem is here:

https://github.com/uTox/uTox/blob/b9f1054080d7f719b810a47441147d96c39c0d77/src/av/video.c#L322

the time it takes to capture and process the frame is not taken into account. to the sleep delay is alway wrong. and therfore the FPS value is very different from what you actually set.
this is confusing.

you can see a "hacky" solution here:

https://github.com/zoff99/uTox/blob/88cd8620f30b2d82ecdee0cfea9e3e2b6a715bdb/src/av/video.c#L341

**Comment by GrayHatter** [comment]
I clicked to your hacky solution, and couldn't even read the code because I was astonished by that brace style... 

Are you being held hostage? Do you need us to come save you? Are the terrorists holding you forcing you to use that brace style? Did you try telling them that forcing someone to READ that brace style is is a crime against humanity? Never mind the amount of suffering it must cause to WRITE code in that formatting?

how far off is the actual FPS from expected?

**Comment by zoff99** [comment]
very far. need to enter 70fps to get around 25fps.
depends on the system i guess.
its just crappy as it is now.
so either instead of "FPS" let the user enter "ms" delay,
or really get the FPS correct.
getting FPS correct would be the better solution

**allman style ruleZ, K&R sucks eggs**

**Comment by GrayHatter** [comment]
@zoff99 you made a small typo in your post. I fixed it for you... You're welcome! :D

**Comment by zoff99** [comment]
so this is the typical way of handling things? making fun of people, but not resolving a bug.
ok.

**Comment by Sami32** [comment]
https://github.com/uTox/uTox/issues/1149

**Comment by Nadahar** [comment]
> I clicked to your hacky solution, and couldn't even read the code because I was astonished by that brace style...

> Are you being held hostage? Do you need us to come save you? Are the terrorists holding you forcing you to use that brace style? Did you try telling them that forcing someone to READ that brace style is is a crime against humanity? Never mind the amount of suffering it must cause to WRITE code in that formatting?

This is by far the worst I've ever seen on GitHub. It reminds me of how "newcomers" were treated when they joined a new channel on IRC back in the 90's. I never understood what the motivation was behind such behavior, and I still don't.

I thought the goal with open source was to collaborate. Such behavior discourages collaboration and can only contribute to kill a project as I see it. Nobody is born "experts" and nobody improves their skill by being made fun of. We should share our knowledge and experience, not try to strike down others. In addition, brace style is just that, *style*. What's beautiful to one person is ugly to another, and some care about style while others don't.

Although I agree that the code can be slightly confusing to read with the inconsistent style, it's seen *so much* worse. The code in question here is *nothing* when it comes to unreadable code.

As a friendly advise, I'd suggest a complete attitude refactoring.
