### ISSUE TITLE
window_x / window_y is ignored on uTox startup

### ISSUE THREAD

**Issue by g4jc** [uTox/uTox#1400]
### Overview

1. uTox version: 0.17.1 [current head](https://github.com/uTox/uTox/commit/aa6bc0829775925d4a64a464c24df4c64940aa81)
2. Operating system: GNU/Linux / Windows (tested on both)
3. Desktop Environment/Window Manager (Linux/BSD only): XFCE / Metro (Win8)

### Issue
* Set a custom window_x and window_y in utox_save.ini or move the window around and close uTox. It will update the variables in this file.
* Custom setting is ignored and starts at 0,0 window location anyway.

UI bug.

**Comment by avoidr** [comment]
Thanks!

I've fixed this now, you can check the `window_coord` branch.

But I've found a new issue. Apparently there is some kind of off-by-one when saving the value back to the file. The x and y values get incremented by one, so next time you run uTox, it will be x+1,y+1… I'm looking into this, too.

**Comment by avoidr** [comment]
@g4jc, can you please test this commit that was referenced here? This exact commit, please.

**Comment by g4jc** [comment]
Thanks for the quick fix! 👍  I can confirm this works.

I was unable to re-produce the off-by-one, it sticks the window to the correct location now.

**Comment by avoidr** [comment]
Thanks for your quick response and verification! I appreciate it.

>I was unable to re-produce the off-by-one, it sticks the window to the correct location now.

Oh-oh. That's not actually good news. I am definitely seeing an off-by-one here on my side. I'm thinking maybe it has to do with my window manager, but I am not sure. Could you please checkout the `window_coord_debug` branch and see if you get any mismatching coords at the end when you close utox?

What I have found out is that the offset is exactly the window border width that my window manager (dwm) sets. So subtracting the border width from the translated coordinates makes it work for me.

P.S.: Have you tested it on Linux and Windows?

**Comment by g4jc** [comment]
I can confirm it works on Windows 7 and Windows 8. However, there is something strange still happening on GNU/Linux. I haven't had time to debug it further, but the current `window_coord_debug` is actually crashing for me and doesn't appear to be saving the coordinates in all cases. This is using XFCE4.

Here's the log from GNU/Linux: https://paste.debian.net/plain/1119376

I will try to test it on another desktop environment when I have time.

**Comment by avoidr** [comment]
>but the current window_coord_debug branch is actually crashing for me and doesn't appear to be saving the coordinates in all cases.

It's crashing for me too, sometimes. When I close utox, it aborts sometimes too early and utox never gets to save the config. Is this the behaviour you are seeing? If so, I believe #1312 will fix it, which I will review and merge hopefully soon.

Does it crash the same way that you observe, on `develop`, too?

>I will try to test it on another desktop environment when I have time.

Please do!

**Comment by avoidr** [comment]
I've rebased `window_coord{,debug}`, so now you can compile with latest openal.

**Comment by avoidr** [comment]
Merged that one commit, because it fixes the issue, and the other thing is a separate issue which may be irrelevant, seeing how it's not an issue on Xfce, especially. And if it bothers someone, they'll complain.

@g4jc, thanks for the issue!
